<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/simple.css');?>
    <script type="text/javascript"
            src="http://www.google.com/jsapi"></script>
    <script type="text/javascript">
            google.load("jquery", "1.3.2");
            google.load("jqueryui", "1.7.2");
    </script>
   <?php echo $this->jQuery()->addStylesheet($this->baseUrl() . '/css/jquery-ui-1.7.2.custom.css'); ?>

</head>
<body>

   <div>
    <?php echo $this->layout()->content; ?>
   </div>
   
<div id="footer"></div>
</body>
</html>